export default {
  listGame: [
    { id: 1, name: 'Jogo da Velha', description: 'Tentar fazer sequência de 3 X ou O', path: 'jogoVelha' },
    { id: 1, name: 'Jogo da Memória', description: 'Tentar achar os pares de todas as fichas', path: 'jogoMemoria' },
    { id: 1, name: 'Caça Palavras', description: 'Localizar todas as palavras solicitadas', path: 'cacaPalavra' },
    { id: 1, name: 'Jogo do Teste', description: 'Testar a paciência do programador', path: 'jogoVelha' },
    { id: 1, name: 'Jogo do Teste', description: 'Testar a paciência do programador', path: 'jogoVelha' },
    { id: 1, name: 'Jogo do Teste', description: 'Testar a paciência do programador', path: 'jogoVelha' },
    { id: 1, name: 'Jogo do Teste', description: 'Testar a paciência do programador', path: 'jogoVelha' },
    { id: 1, name: 'Jogo do Teste', description: 'Testar a paciência do programador', path: 'jogoVelha' },
    { id: 1, name: 'Jogo do Teste', description: 'Testar a paciência do programador', path: 'jogoVelha' },
    { id: 1, name: 'Jogo do Teste', description: 'Testar a paciência do programador', path: 'jogoVelha' },
    { id: 1, name: 'Jogo do Teste', description: 'Testar a paciência do programador', path: 'jogoVelha' },
    { id: 1, name: 'Jogo do Teste', description: 'Testar a paciência do programador', path: 'jogoVelha' },
    { id: 1, name: 'Jogo do Teste', description: 'Testar a paciência do programador', path: 'jogoVelha' }
  ],
  imagesCute: [
    {path: require('../../assets/fofas/01.jpg'), class: 'imgHide', name: '01', show: false, find: false},
    {path: require('../../assets/fofas/03.jpg'), class: 'imgHide', name: '02', show: false, find: false},
    {path: require('../../assets/fofas/02.jpg'), class: 'imgHide', name: '03', show: false, find: false},
    {path: require('../../assets/fofas/04.jpg'), class: 'imgHide', name: '04', show: false, find: false},
    {path: require('../../assets/fofas/05.jpg'), class: 'imgHide', name: '05', show: false, find: false},
    {path: require('../../assets/fofas/06.jpg'), class: 'imgHide', name: '06', show: false, find: false},
    {path: require('../../assets/fofas/07.jpg'), class: 'imgHide', name: '07', show: false, find: false},
    {path: require('../../assets/fofas/08.jpg'), class: 'imgHide', name: '08', show: false, find: false},
    {path: require('../../assets/fofas/09.jpg'), class: 'imgHide', name: '09', show: false, find: false},
    {path: require('../../assets/fofas/10.jpg'), class: 'imgHide', name: '10', show: false, find: false},
    {path: require('../../assets/fofas/11.jpg'), class: 'imgHide', name: '11', show: false, find: false},
    {path: require('../../assets/fofas/12.jpg'), class: 'imgHide', name: '12', show: false, find: false},
    {path: require('../../assets/fofas/13.jpg'), class: 'imgHide', name: '13', show: false, find: false},
    {path: require('../../assets/fofas/14.jpg'), class: 'imgHide', name: '14', show: false, find: false},
    {path: require('../../assets/fofas/15.jpg'), class: 'imgHide', name: '15', show: false, find: false},
    {path: require('../../assets/fofas/16.jpg'), class: 'imgHide', name: '16', show: false, find: false},
    {path: require('../../assets/fofas/17.jpg'), class: 'imgHide', name: '17', show: false, find: false},
    {path: require('../../assets/fofas/18.jpg'), class: 'imgHide', name: '18', show: false, find: false},
    {path: require('../../assets/fofas/19.jpg'), class: 'imgHide', name: '19', show: false, find: false},
    {path: require('../../assets/fofas/20.jpg'), class: 'imgHide', name: '20', show: false, find: false},
    {path: require('../../assets/fofas/21.jpg'), class: 'imgHide', name: '21', show: false, find: false}
  ]
}
